[package]
name = "gypsys_grab_v4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"                 # Logging library for Rust
simple-logging = "0.12"    # Simple logging to a file
notify = "5.0"             # For file system event watching
